name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.jaycelmarie}}
        DOCKER_PASSWORD: ${{secrets.jammy1311891}}
      run: |
        docker login -u $jaycelmarie -p $jammy1311891
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jaycelmarie/first-repo:$(date +%s)
      
    - name: Docker push
      run: docker push ${{secrets.jaycelmarie}}/first-repo
